<?php
	/**
	 * bodyHeading.inc
	 * Contains the heading for each THINKer page
	 *
	 * @author Cory Gehr
	 */
?>
	<div id='infoHeader'>

	</div>
	<div id='header'>
		<img src="<?php echo $styleDir . "/images/logo.png"; ?>" alt="Penn State Dance Marathon">
		<link rel="shortcut icon" href="http://thon.org/sites/default/files/favicon.ico" type="image/vnd.microsoft.icon" />
	</div>
	<div id='primaryNav'>

	</div>
	<div id='wrapper'>
		<div id='content'>