<?php
	/**
	 * head.inc
	 * Contains the HTML Header for THINKer
	 *
	 * @author Cory Gehr
	 */

?>
    <title>THINKer</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <link href='<?php echo $styleDir . "/css/screen.css"; ?>' rel='stylesheet' type='text/css' media='screen' />
	<script type='text/javascript' src="<?php echo $styleDir . "/js/jquery-1.11.0.min.js"; ?>"></script>
	<link rel="shortcut icon" href="http://thon.org/sites/default/files/favicon.ico" type="image/vnd.microsoft.icon" />
