<?php
	/**
	 * bodyHeading.inc
	 * Contains the heading for each THINKer page
	 *
	 * @author Cory Gehr
	 */
?>
	<div id='head-wrapper'>
		<div id='head-container'>
			<a href='<?php echo BASE_URL; ?>'><img src='View/html/style/sample/images/logo.png' alt='THINKer'></a>
			<p class='user-info'>
				Welcome!
			</p>
			<div id='head-usernav'>
				<ul>
					<li><a href='#'>Sample Link</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div id='main-wrapper'>
		<div id='content-container'>