<?php
	/**
	 * head.inc
	 * Contains the HTML Header for THINKer
	 *
	 * @author Cory Gehr
	 */

?>
	<title>THINKer</title>
	<link rel='stylesheet' href='<?php echo $styleDir . '/css/screen.css'; ?>' type='text/css' media='screen'>
	<link href='<?php echo $styleDir . '/css/jquery/jquery-ui-1.10.4.custom.min.css'; ?>' rel='stylesheet'>
	<meta http-equiv='Content-Type' content='text/html;charset=utf-8'>
	<meta http-equiv="cache-control" content="no-cache">
	<link rel="shortcut icon" href="<?php echo $styleDir . '/images/favicon.ico'; ?>" type="image/x-icon">
	<link rel="icon" href="<?php echo $styleDir . '/images/favicon.ico'; ?>" type="image/x-icon">
	<!-- jQuery 2.1.0 and components -->
	<script type='text/javascript' src='<?php echo $styleDir . '/js/jquery-2.1.0.min.js'; ?>'></script>
	<script type='text/javascript' src='<?php echo $styleDir . '/js/jquery-ui-1.10.4.custom.min.js'; ?>'></script>
	<script type='text/javascript' src='<?php echo $styleDir . '/js/jquery.validate-1.11.1.min.js'; ?>'></script>
	<script type='text/javascript' src='<?php echo $styleDir . '/js/jquery.validate-additional-methods.min.js'; ?>'></script>
	<script type='text/javascript' src='<?php echo $styleDir . '/js/jquery.tablesorter-2.0.5.min.js'; ?>'></script>
	<script type='text/javascript' src='<?php echo $styleDir . '/js/jquery.tablesorter.pager.js'; ?>'></script>